### ISSUE TITLE
Is this has been tested with Pi3 ? Pi4 ?

### ISSUE THREAD

**Issue by brunetton** [danielappelt/caPiture#3]
Hi

I'm super interested in this project as I plan to record live sessions with a Raspberry. I wanted to know: did you succeeded recording 18 tracks with a Raspberry Pi 3 without errors ? 

Thanks a lot

**Comment by eamonn-tobin** [comment]
Hi,

Sorry for the very late reply.
We succeeded in recording 18 channels with a RPI3 but only for 8 minutes or so, after that errors started occuring. Hence the 480 seconds timer for jack-capture in the rec script.
Good luck.

**Comment by brunetton** [comment]
> Hi,
> 
> Sorry for the very late reply. We succeeded in recording 18 channels with a RPI3 but only for 8 minutes or so, after that errors started occuring. Hence the 480 seconds timer for jack-capture in the rec script. Good luck.

Thanks for your reply.
Since my question I did many tests avec succeeded to record 18 channels with jack_capture using Flac format for 3h without any glitches using a RPi4 :) (I lunched 2 jack_capture processes in parallel as FLAC [is limited to 8 channels](https://github.com/xiph/flac/issues/319))

I'll document it "soon" somewhere, very probably to a repo, as I started from your code (thanks for this :+1:) but derived quite far from it (mainly by using systemd to start the script, which is way better in terms of global stability !). I'll put the link here in this issue.

**Comment by brunetton** [comment]
I finally tool some time and released a first version of my script (again, very inspired by your work so thank you !)

As I forked quite a lot I initiated a separate project. I really hope you don't mind I did it !

https://github.com/brunetton/caPiture-ng

Hope it could help :)

**Comment by eamonn-tobin** [comment]
Hey, that's great news. Congratulations on the new release, it looks good. I'm glad you could use this project as a start.
